import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Header from '../components/Header';
import styles from '../styles/Home.module.css';

export default function Users({ users }: { users: any }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>Users Page</h1>
        <ul>
          {users?.data.map(
            (
              user: {
                id: number;
                email: string;
                first_name: string;
                last_name: string;
              },
              index: number
            ) => (
              <li key={index}>
                <Link href={`/users/${user.id}`}>
                  {user.first_name} {user.last_name}
                </Link>

                <div>{user.email}</div>
              </li>
            )
          )}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

// This function gets called at build time
export async function getStaticProps() {
  // Call an external API endpoint to get users
  const res = await fetch('https://reqres.in/api/users');
  const users = await res.json();

  // By returning { props: { users } }, the Blog component
  // will receive `users` as a prop at build time
  return {
    props: {
      users,
    },
  };
}
